-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgF1yekecoADcuIU+c
Lf9T+EodBW8sqnYALbf/0lg+1kCgCgYIKoZIzj0DAQehRANCAARuaPxPWOjr1ARC
YGTPUK2DEU4yn+AW9M5VWs+zPhoMAxjThWGFKIlb0uPzljaoyG1fGBAr0Kwgp3iQ
z//xx96B
-----END PRIVATE KEY-----